### ISSUE TITLE
Node Alpine doesn't works well with `@react-email/preview-server:5.21` and `react-email: 5.2.1` due to env -S args.

### ISSUE THREAD

**Issue by RSickenberg** [resend/react-email#2792]
### Describe the Bug

While starting my dev server I had an update from dependabot to these two components and this error happened.

`/usr/bin/env: unrecognized option: S`.

### What is affected (leave empty if unsure)

Preview Server

### Link to the code that reproduces this issue

Simply this docker-compose element.

```yml
  react-email:
    image: node:24-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: npm run email:dev
    ports:
      - "3001:3001"
    env_file:
      - .env
```

```
npm command is = "email:dev": "email dev -p 3001"
```

### To Reproduce

Start the container.

### Expected Behavior

To behave like 2.1.1.

### What's your node version? (if relevant)

24.12.0

**Comment by qe-romanvasek** [comment]
Same problem on Windows using node 24 and bun 1.3.5

**Comment by droutin** [comment]
Last working version is [4.3.2](https://www.npmjs.com/package/react-email/v/4.3.2)

**Comment by xFGhoul** [comment]
This happens with bun as well, what is the cause?

**Comment by RSickenberg** [comment]
> Last working version is [4.3.2](https://www.npmjs.com/package/react-email/v/4.3.2)

`5.1.1` is working for me.

**Comment by droutin** [comment]
> > Last working version is [4.3.2](https://www.npmjs.com/package/react-email/v/4.3.2)
> 
> `5.1.1` is working for me.

are you on windows?

**Comment by RSickenberg** [comment]
> > > Last working version is [4.3.2](https://www.npmjs.com/package/react-email/v/4.3.2)
> > 
> > `5.1.1` is working for me.
> 
> are you on windows?

MacOS while using Docker with `node:24-alpine`.

**Comment by DiiiaZoTe** [comment]
> Same problem on Windows using node 24 and bun 1.3.5

+1 Same issue here...

**Comment by RSickenberg** [comment]
Deps with `5.2.2` releases also doesn't work for me

<img width="1048" height="504" alt="Image" src="https://github.com/user-attachments/assets/8c414315-7c5a-4a4c-82a6-440fbc1d67d4" />

**Comment by droutin** [comment]
Same issue on 5.2.2

<img width="1015" height="321" alt="Image" src="https://github.com/user-attachments/assets/c45a4e5c-4b62-4cb6-8c1a-4ec31e578efc" />

**Comment by agentHits** [comment]
This helped me, I put all the emails in the emails folder and it worked

"email:dev": "email dev --dir emails --port 3000",

I run it using the command 

> **bun run email:dev** 

> I apologize, it works on a MacBook with this command, but it refuses to work on Windows.


<img width="1327" height="820" alt="Image" src="https://github.com/user-attachments/assets/d3fbe4ba-d959-4d1f-be4d-3bbb5b4efd5e" />



**i used for install package.json** 

```
bun add react-email -D -E
bun add @react-email/components react react-dom -E
```

**Comment by agentHits** [comment]
**What's surprising is that I installed npm and everything works on Windows 11, but via Bun it doesn't work on Windows 11.**

**Comment by RSickenberg** [comment]
Still not working with the 5.2.5 release.

<img width="1084" height="506" alt="Image" src="https://github.com/user-attachments/assets/47e0c376-4298-497f-9584-b6d08e71d19f" />

**Comment by bennajah** [comment]
same issue with 

- react-email: `5.2.5` 
- bun: `1.3.7`
- windows 11: `25H2 (OS Build 26200.7628)` 

```PS
error: interpreter executable "-S" not found in %PATH%

Bun failed to remap this bin to its proper location within node_modules.
This is an indication of a corrupted node_modules directory.

Please run 'bun install --force' in the project root and try
it again. If this message persists, please open an issue:
https://github.com/oven-sh/bun/issues

error: script "email:dev" exited with code 255
```

**Comment by gabrielmfern** [comment]
I expect #2915 to fix it, can you all try it out with

```sh
npm i https://pkg.pr.new/resend/react-email@2915
```

and let me know if it works?

**Comment by bennajah** [comment]
> https://pkg.pr.new/resend/react-email@2915

now getting another error

with `bun run email dev` and `bunx email dev`
```PS
PS D:\projects\my-app> bun run email dev
    React Email 5.3.0-canary.2
    Running preview at:          http://localhost:3000

  ⠋ Getting react-email preview server ready...
Error: Cannot find module 'next'
Require stack:
- C:\Users\benna\.react-email\_index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1421:15)
    at require.resolve (node:internal/modules/helpers:163:19)
    at jitiResolve (D:\projects\my-app\node_modules\jiti\dist\jiti.cjs:1:148703)
    at jitiRequire (D:\projects\my-app\node_modules\jiti\dist\jiti.cjs:1:150290)
    at Function.import (D:\projects\my-app\node_modules\jiti\dist\jiti.cjs:1:158307)
    at startDevServer (file:///D:/projects/my-app/node_modules/react-email/dist/index.js:7782:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
    at async Command.dev (file:///D:/projects/my-app/node_modules/react-email/dist/index.js:7882:27) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\benna\\.react-email\\_index.js' ]
  ✖ Getting react-email preview server ready...


shutting down dev server
```

with `bun run --bun email dev`

```PS
PS D:\projects\my-app> bun run --bun email dev
    React Email 5.3.0-canary.2
    Running preview at:          http://localhost:3000

  ⠋ Getting react-email preview server ready...
  ✖ Getting react-email preview server ready...


shutting down dev server
```

with `bunx --bun email dev`

```PS
PS D:\projects\my-app> bunx --bun email dev
  🔍 Resolving [1/1] error: "git clone" for "@D:/projects/my-app/node_modules/react-email/dist/index.js" failed
error: InstallFailed cloning repository for @D:/projects/my-app/node_modules/react-email/dist/index.js
error: @D:/projects/my-app/node_modules/react-email/dist/index.js failed to resolve
```
